# Generated by Django 6.0 on 2026-01-07 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('formacao', models.CharField(choices=[('graduacao', 'Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], default='graduacao', max_length=15)),
                ('celular', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'pesquisador',
            },
        ),
    ]
