# Generated by Django 6.0 on 2026-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0019_replace_preferencia_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='whatsapp_apikey',
            field=models.CharField(blank=True, help_text='Chave (apikey) gratuita do CallMeBot para envio de WhatsApp. O pesquisador gera a chave adicionando o contato do CallMeBot e enviando a mensagem de autorização. Necessária apenas se a preferência de comunicação for por celular/WhatsApp.', max_length=100, null=True),
        ),
    ]
