# Generated by Django 6.0 on 2026-07-14 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0020_pesquisador_whatsapp_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessao_ativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão Ativa',
                'verbose_name_plural': 'Sessões Ativas',
            },
        ),
    ]
