# Generated by Django 6.0 on 2026-07-14 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0021_sessaoativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('acao', models.CharField(max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('caminho', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ação',
                'verbose_name_plural': 'Registros de Ações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
