# Generated by Django 6.0 on 2026-07-26 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0022_registroacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('projetos', 'Projetos'), ('dashboard', 'Dashboard'), ('pesquisadores', 'Pesquisadores'), ('avisos', 'Avisos'), ('ajustes', 'Ajustes'), ('registro_acoes', 'Registro de Ações')], max_length=30)),
                ('nivel', models.CharField(choices=[('nenhum', 'Sem acesso'), ('ver', 'Ver'), ('editar', 'Ver e editar')], default='nenhum', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_pagina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a Página',
                'verbose_name_plural': 'Acessos a Páginas',
                'unique_together': {('user', 'area')},
            },
        ),
    ]
