# Generated by Django 6.0 on 2026-01-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('sig_id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('data_ent_sig', models.DateField(blank=True, null=True)),
                ('data_lib_analise', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('class_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_pesq', models.CharField(blank=True, max_length=100, null=True)),
                ('desenvolvimento_tecnologico', models.BooleanField(default=False)),
                ('multicentrico', models.BooleanField(default=False)),
                ('especialidade_proponente', models.CharField(blank=True, max_length=100, null=True)),
                ('linhas_pesq', models.TextField(blank=True, null=True)),
                ('inicio_coleta', models.DateField(blank=True, null=True)),
                ('fim_coleta', models.DateField(blank=True, null=True)),
                ('data_aprovacao_inst', models.DateField(blank=True, null=True)),
                ('parecer_cep', models.CharField(blank=True, max_length=100, null=True)),
                ('data_parecer_cep', models.DateField(blank=True, null=True)),
                ('papel_HUB_multi', models.CharField(blank=True, max_length=100, null=True)),
                ('parceria_HUB_UNB', models.BooleanField(default=False)),
                ('HUB_proponente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('nome_unidade', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pesquisa', serialize=False, to='projetos.projeto')),
                ('sig_id_pesq', models.CharField(blank=True, max_length=100, null=True)),
                ('pesq_status', models.CharField(blank=True, max_length=100, null=True)),
                ('relatorio_entrege', models.BooleanField(default=False)),
                ('pacientes_recrutados', models.IntegerField(default=0)),
                ('divulgacao_resultados', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='pesquisadores',
            field=models.ManyToManyField(through='projetos.Participacao', to='contas.pesquisador'),
        ),
        migrations.AddField(
            model_name='participacao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
        ),
        migrations.CreateModel(
            name='Fomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fonte', models.CharField(max_length=100)),
                ('tipo_fonte', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fomentos', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Envolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.unidade')),
            ],
            options={
                'unique_together': {('unidade', 'projeto')},
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='unidades',
            field=models.ManyToManyField(through='projetos.Envolve', to='projetos.unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='participacao',
            unique_together={('pesquisador', 'projeto')},
        ),
    ]
