# Generated by Django 6.0 on 2026-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_sig_id_pesq_delete_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='sig_id_projeto',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
