# Generated by Django 6.0 on 2026-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_sig_id_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='parecer_cep',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('na', 'N/A')], max_length=10, null=True),
        ),
    ]
