# Generated by Django 6.0 on 2026-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projeto_parecer_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_envolve',
            field=models.CharField(blank=True, choices=[('envolve', 'Envolve seres humanos'), ('nao_envolve', 'Não envolve seres humanos')], max_length=20, null=True),
        ),
    ]
