# Generated by Django 6.0 on 2026-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_projeto_tipo_envolve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tipo_envolve',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_pesq',
            field=models.CharField(blank=True, choices=[('com_seres_humanos', 'Envolve seres humanos'), ('sem_seres_humanos', 'Não envolve seres humanos')], max_length=30, null=True),
        ),
    ]
