# Generated by Django 6.0 on 2026-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_remove_projeto_tipo_envolve_alter_projeto_tipo_pesq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoInstitucional',
            fields=[
                ('nome_classificacao', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Classificação Institucional',
                'verbose_name_plural': 'Classificações Institucionais',
            },
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='class_inst',
        ),
        migrations.AddField(
            model_name='projeto',
            name='classificacoes',
            field=models.ManyToManyField(blank=True, to='projetos.classificacaoinstitucional'),
        ),
    ]
