# Generated by Django 6.0 on 2026-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_classificacaoinstitucional_remove_projeto_class_inst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPesquisa',
            fields=[
                ('nome_tipo', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tipo de Pesquisa',
                'verbose_name_plural': 'Tipos de Pesquisa',
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_pesq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
