# Generated by Django 6.0 on 2026-04-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_tipopesquisa_alter_projeto_tipo_pesq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='especialidade_proponente',
            field=models.CharField(blank=True, choices=[('Anestesiologia', 'Anestesiologia'), ('Arquivologia', 'Arquivologia'), ('Biblioteconomia', 'Biblioteconomia'), ('Cardiologia', 'Cardiologia'), ('Ciências biológicas', 'Ciências biológicas'), ('Cirurgia do aparelho digestivo', 'Cirurgia do aparelho digestivo'), ('Cirurgia geral', 'Cirurgia geral'), ('Cirurgia oncológica', 'Cirurgia oncológica'), ('Cirurgia pediátrica', 'Cirurgia pediátrica'), ('Cirurgia vascular', 'Cirurgia vascular'), ('Cirurgia videolaparoscópica', 'Cirurgia videolaparoscópica'), ('Clínica médica', 'Clínica médica'), ('Coloproctologia', 'Coloproctologia'), ('Dermatologia', 'Dermatologia'), ('Doenças infecto parasitárias', 'Doenças infecto parasitárias'), ('Endocrinologia', 'Endocrinologia'), ('Endocrinologia pediátrica', 'Endocrinologia pediátrica'), ('Enfermagem', 'Enfermagem'), ('Engenharia de energia ciência de dados', 'Engenharia de energia ciência de dados'), ('Epidemiologia-saúde coletiva', 'Epidemiologia-saúde coletiva'), ('Farmácia', 'Farmácia'), ('Fisioterapia', 'Fisioterapia'), ('Gastroenterologia', 'Gastroenterologia'), ('Geriatria', 'Geriatria'), ('Ginecologia', 'Ginecologia'), ('Hepatologia', 'Hepatologia'), ('Infectologia', 'Infectologia'), ('Mastologia', 'Mastologia'), ('Medicina', 'Medicina'), ('Medicina intensiva', 'Medicina intensiva'), ('Medicina Tropical', 'Medicina Tropical'), ('Microbiologia', 'Microbiologia'), ('Nefrologia', 'Nefrologia'), ('Neurologia', 'Neurologia'), ('Nutrição', 'Nutrição'), ('Obstetrícia', 'Obstetrícia'), ('Odontologia', 'Odontologia'), ('Oftalmologia', 'Oftalmologia'), ('Onco-hematologia', 'Onco-hematologia'), ('Oncologia clínica', 'Oncologia clínica'), ('Otorrinolaringologia', 'Otorrinolaringologia'), ('Patologia', 'Patologia'), ('Pedagogia', 'Pedagogia'), ('Pediatria', 'Pediatria'), ('Pneumologia', 'Pneumologia'), ('Processamento de dados', 'Processamento de dados'), ('Psicologia', 'Psicologia'), ('Psiquiatria', 'Psiquiatria'), ('Radiologia', 'Radiologia'), ('Radioterapia', 'Radioterapia'), ('Reumatologia', 'Reumatologia'), ('Saúde coletiva', 'Saúde coletiva'), ('Serviço social', 'Serviço social'), ('Terapia ocupacional', 'Terapia ocupacional'), ('Transplante', 'Transplante'), ('Urologia', 'Urologia'), ('outros', 'outros')], max_length=100, null=True),
        ),
    ]
