# Generated by Django 6.0 on 2026-04-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_alter_projeto_especialidade_proponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadeProponente',
            fields=[
                ('nome_especialidade', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Especialidade do Proponente',
                'verbose_name_plural': 'Especialidades do Proponente',
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='especialidade_proponente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
