# Generated by Django 6.0 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_especialidadeproponente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoProponente',
            fields=[
                ('nome_instituicao', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Instituição Proponente',
                'verbose_name_plural': 'Instituições Proponentes',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='instituicao_proponente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
