# Generated by Django 6.0 on 2026-04-15 22:45

from django.db import migrations, models


def normalizar_desenvolvimento_tecnologico(apps, schema_editor):
    Projeto = apps.get_model('projetos', 'Projeto')

    Projeto.objects.filter(desenvolvimento_tecnologico__in=['1', 'True', 'true', 'SIM', 'Sim']).update(
        desenvolvimento_tecnologico='sim'
    )
    Projeto.objects.filter(desenvolvimento_tecnologico__in=['0', 'False', 'false', 'NAO', 'Não', 'Nao']).update(
        desenvolvimento_tecnologico='nao'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_instituicaoprop_and_projeto_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='desenvolvimento_tecnologico',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('duvida', 'Em dúvida')], max_length=10, null=True),
        ),
        migrations.RunPython(normalizar_desenvolvimento_tecnologico, migrations.RunPython.noop),
    ]
