# Generated by Django 6.0 on 2026-04-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_alter_projeto_desenvolvimento_tecnologico'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_fomento',
            field=models.CharField(blank=True, choices=[('EDITAL DE AGÊNCIAS DE FOMENTO', 'EDITAL DE AGÊNCIAS DE FOMENTO'), ('PÚBLICO NACIONAL', 'PÚBLICO NACIONAL'), ('PÚBLICO INTERNACIONAL', 'PÚBLICO INTERNACIONAL'), ('PRIVADO INTERNACIONAL', 'PRIVADO INTERNACIONAL'), ('PRIVADO NACIONAL', 'PRIVADO NACIONAL'), ('PRÓPRIO PESQUISADOR', 'PRÓPRIO PESQUISADOR'), ('OUTRA', 'OUTRA')], max_length=50, null=True),
        ),
    ]
