# Generated by Django 6.0 on 2026-04-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_projeto_tipo_fomento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalHubBrasil',
            fields=[
                ('nome_hospital', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Hospital da Rede HUBrasil',
                'verbose_name_plural': 'Hospitais da Rede HUBrasil',
            },
        ),
        migrations.CreateModel(
            name='ParceriaHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.hospitalhubbrasil')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'unique_together': {('hospital', 'projeto')},
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='hospitais_parceiros',
            field=models.ManyToManyField(blank=True, through='projetos.ParceriaHospital', to='projetos.hospitalhubbrasil'),
        ),
    ]
