# Generated by Django 6.0 on 2026-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_hospitalhubbrasil_parceriahospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='formalizacao_instrumento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
