# Generated by Django 6.0 on 2026-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_projeto_formalizacao_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='formalizacao_instrumento',
            field=models.BooleanField(default=False),
        ),
    ]
