# Generated by Django 6.0 on 2026-06-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0020_pesquisador_whatsapp_apikey'),
        ('projetos', '0020_linha_pesquisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(default='Aviso sobre seu projeto de pesquisa', max_length=255)),
                ('mensagem', models.TextField(default='Olá {nome},\n\nEste é um aviso periódico referente ao seu projeto de pesquisa "{titulo}" (SIG {sig_id}).\n\nPor favor, mantenha as informações do projeto atualizadas no sistema ELO.\n\nAtenciosamente,\nEquipe de Gestão da Pesquisa')),
                ('intervalo_dias', models.PositiveIntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Aviso',
                'verbose_name_plural': 'Configuração de Avisos',
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='papel_HUB_multi',
            field=models.CharField(blank=True, choices=[('coordenador', 'Coordenador'), ('coparticipante', 'Coparticipante'), ('participante', 'Participante')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AvisoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('detalhe', models.TextField(blank=True)),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.pesquisador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Aviso Enviado',
                'verbose_name_plural': 'Avisos Enviados',
                'ordering': ['-data_envio'],
            },
        ),
    ]
