# Generated by Django 6.0 on 2026-07-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0022_renomear_funcao_lider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvedorFomento',
            fields=[
                ('nome_provedor', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Provedor de Fomento',
                'verbose_name_plural': 'Provedores de Fomento',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='provedor_fomento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
