# Generated by Django 6.0 on 2026-07-14 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0023_provedorfomento_projeto_provedor_fomento'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='sub_tipo_pesq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SubTipoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sub_tipo', models.CharField(max_length=255)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='projetos.tipopesquisa')),
            ],
            options={
                'verbose_name': 'Sub-tipo de Pesquisa',
                'verbose_name_plural': 'Sub-tipos de Pesquisa',
                'unique_together': {('nome_sub_tipo', 'tipo')},
            },
        ),
    ]
