# Generated by Django 6.0 on 2026-07-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0024_projeto_sub_tipo_pesq_subtipopesquisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_ativo', models.BooleanField(default=True, verbose_name='Alerta de CEP ativo')),
                ('prazo_cep_meses', models.PositiveIntegerField(default=6, verbose_name='Prazo para parecer do CEP (meses após aprovação institucional)')),
                ('assunto_cep', models.CharField(default='Pendência: parecer do CEP do seu projeto de pesquisa', max_length=255)),
                ('mensagem_cep', models.TextField(default='Olá {nome},\n\nO projeto "{titulo}" (SIG {sig_id}) foi aprovado institucionalmente em {data_aprovacao} e ainda não possui parecer do CEP registrado.\n\nO parecer do CEP é esperado em até {prazo_cep} meses após a aprovação institucional. Por favor, providencie a submissão/registro do parecer.\n\nAtenciosamente,\nEquipe de Gestão da Pesquisa')),
                ('relatorio_ativo', models.BooleanField(default=True, verbose_name='Alerta de relatório ativo')),
                ('prazo_relatorio_meses', models.PositiveIntegerField(default=12, verbose_name='Prazo para relatório (meses após parecer do CEP)')),
                ('assunto_relatorio', models.CharField(default='Pendência: relatório do seu projeto de pesquisa', max_length=255)),
                ('mensagem_relatorio', models.TextField(default='Olá {nome},\n\nPassou-se mais de {prazo_relatorio} meses desde o parecer do CEP do projeto "{titulo}" (SIG {sig_id}), emitido em {data_parecer_cep}.\n\nÉ necessário apresentar o relatório do projeto. Por favor, providencie o envio.\n\nAtenciosamente,\nEquipe de Gestão da Pesquisa')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Alertas',
                'verbose_name_plural': 'Configuração de Alertas',
            },
        ),
    ]
