# Generated by Django 6.0 on 2026-07-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0025_configuracaoalertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField(help_text='Variáveis disponíveis: {nome}, {titulo}, {sig_id}.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aviso',
                'verbose_name_plural': 'Tipos de Aviso',
                'ordering': ['nome'],
            },
        ),
    ]
